### ISSUE TITLE
Paths issue on Windows

### ISSUE THREAD

**Issue by mircofranzago** [atlanmod/emfviews#2]
Hi,
I downloaded myFirstViewTutorial from examples folder.
With Eclipse Kepler SR2, Epsilon 1.1_SR1 and EMF Views 0.2.0.201407021945 on Windows, I was unable to open the publicationsAndBooks.eviewtype file using EMF Views Editor due a problem with paths. Opening the file with the text editor, I had to manually change the publicationsAndBooks.eviewtype file from:

contributingMetamodels=myFirstViewTutorial/metamodels/Publication.ecore,myFirstViewTutorial/metamodels/Book.ecore
correspondenceModel=myFirstViewTutorial/viewtypes/publicationsAndBooks.xmi
correspondenceModelBase=myFirstViewTutorial/viewtypes/publicationsAndBooks.ecl
filtersMetamodel=/myFirstViewTutorial/viewtypes/publicationsAndBooks.ecore

to:

contributingMetamodels=/myFirstViewTutorial/metamodels/Publication.ecore,/myFirstViewTutorial/metamodels/Book.ecore
correspondenceModel=/myFirstViewTutorial/viewtypes/publicationsAndBooks.xmi
correspondenceModelBase=/myFirstViewTutorial/viewtypes/publicationsAndBooks.ecl
filtersMetamodel=/myFirstViewTutorial/viewtypes/publicationsAndBooks.ecore

Adding the "/" at the beginning of the paths (just like the last line "filtersMetamodel"), everything seem to work. I can not try on other operating systems, but on Windows I needed that change, otherwise I got the follow exception and the EMF Views Editor "crash": 

!ENTRY org.eclipse.e4.ui.workbench 4 0 2014-09-02 15:56:44.731
!MESSAGE 
!STACK 0
org.eclipse.emf.ecore.resource.impl.ResourceSetImpl$1DiagnosticWrappedException: java.io.FileNotFoundException: myFirstViewTutorial\metamodels\Publication.ecore (The system cannot find the path specified)

**Comment by fmdkdd** [comment]
The eview and eviewtype files now support relative paths.
