### ISSUE TITLE
EMFView plugin not starting

### ISSUE THREAD

**Issue by antoniocicchetti** [atlanmod/emfviews#3]
I am using Eclipse Oxygen 1.A and cannot get the plugin to work. I have even downloaded a fresh installation of Oxygen 1.C and after installing ATL, Epsilon, and XText tried to import EMFView. Everything seems to be free of errors, however in the second Eclipse instance there is no trace of EMFView (no menu' items, no creation options, no examples). Could you please list in details on what Eclipse Packages are you running the plugins? Since Epsilon itself does not come in a bundle for Oxygen, it would be also important to know what you installed for Epsilon (version/packages of GMF, EMFatic, packages of Epsilon itself). 

Thanks,

Antonio

**Comment by fmdkdd** [comment]
Hi @antoniocicchetti!  I've been meaning to get back to you after Helsinki, but I've been busy with other academic duties.

> (no menu' items, no creation options, no examples).

We are still in the process of polishing examples and tutorials.  Unless you built the editor, there are no obvious signs of EMF Views in Eclipse.

You can check that the plugin is available in your installation.  Then you should be able to call that programmatically at least, or open the `eview` files in `examples/emfviews-tutorial/views` with the built-in EMF Ecore Editor.

Regarding Epsilon versions, we are using 1.4.0.

**Comment by antoniocicchetti** [comment]
Hi again and thanks for the prompt feedback. Indeed I got confused by the tutorials since in them it is possible to see some EMFViews specific icons and commands in the contextual menu. At now I can inspect some of the examples and make some tests. Thanks!
