### ISSUE TITLE
EMFViews Eclipse projects cannot be compiled within Eclipse

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [atlanmod/emfviews#5]
Bonjour,
As I couldn't build EMFViews using Maven (see #4), I tried to import the projects into Eclipse and compile them against an Eclipse target poinited to Eclipse 2018-09 where I added the different dependencies (Epsilon, ATL, XText).
However, I have multiple issues in EMFView projects, including:
- missing source folders, such as src-gen and xtend-gen
- missing packages in declared exported-packages within the Manifest.MF

I suppose the missing packages are located in the missing source folders. I also suppose that this missing folders should be generated by Xtext, but even if I ask Eclipse to clean and compile all the projects, and they already have the XText build nature, they are not generated. Any idea?

I see also a missing dependency on `org.atlanmod.sexp2emf`, which seems not to be available.
Can you provide me further assistance to setup Eclipse for building EMFViews?
Merci beaupcoup
Yosu

**Comment by fmdkdd** [comment]
> I suppose the missing packages are located in the missing source folders

Yes, all these errors stem from not generating the Xtext artifacts.  I've added that step to the `Development setup` part of the readme.

>  they already have the XText build nature, they are not generated. Any idea?

The artifacts are not generated automatically by Xtext, but need to be created manually.  Specifically:

> Before building you'll need to generate the Xtext artifacts (right-click the Mel.xtext and Vpdl.xtext grammars in the Eclipse explorer ▶ Run As ▶ Generate Xtext Artifacts).

Let me know if this works for you.

**Comment by jesus-gorronogoitia** [comment]
Thanks a lot. Now a have a clean and compiled Eclipse workspace for EMFViews
