### ISSUE TITLE
EMFViews cannot be installed from update site in Eclipse 2018-09

### ISSUE THREAD

**Issue by jesus-gorronogoitia** [atlanmod/emfviews#6]
Bonjour,
I also tried to install EMFViews in Eclipse 2018-09 from the update site, but it fails because it depends on org.eclipse.m2m.atl.core.emf [3.8.0, 4.00), but precisely Eclipse 2018-09 installs ATL version 4.0.0.
In MegaM@Rt project we are using as baseline Eclipse for the integrated platform this 2018-09 version. Could be possible you upgrade EMFViews to be compatible with this version and provide a new update site?

Merci beaupcoup
Yosu

**Comment by fmdkdd** [comment]
Sure, we can extend to 4.0. We are actually using 4.0 with Maven and that version does not seem to have issues.

Incidentally, we are in the process of migrating our update site, so please hold on until that is done.

**Comment by jesus-gorronogoitia** [comment]
Great!, Please, keep me informed when you release a new version compatible with Eclipse 2018-09. We are due to release the platform by 15th January. Let me know if EMFViews can be released before so we can integrate it by that date.

**Comment by fmdkdd** [comment]
You should now be able to install EMF Views from our new update site:
https://www.atlanmod.org/updates/emfviews/snapshot

I've tested on a 4.9 Modeling Tools distribution, and it installs correctly after installing Epsilon.

**Comment by fmdkdd** [comment]
@jesus-gorronogoitia That's strange.  I don't get this issue with a fresh Eclipse.  Is there maybe some caching of the update site?  Are you sure you are using the new update site URL and not the old one (atlanmodexp:8080) ?

**Comment by jesus-gorronogoitia** [comment]
@fmdkdd Sorry, you are right, I was still using the old site, now it works for the new one. Sorry for the inconveniences. Merci beaupcoup
